FROM node:alpine

WORKDIR /app/frontend

COPY package*.json .n 
COPY package.json /app/frontend/

RUN npm install

COPY . ./

RUN npm run build 

COPY . ./

EXPOSE 3000

CMD ["npm", "start"]
